run:
  timeout: 2m

linters:
  enable:
    - govet        
    - errcheck     
    - staticcheck  
    - gosimple     
    - unused       
issues:
  exclude-use-default: false
  max-same-issues: 5
  max-issues-per-linter: 0
