FROM golang:1.24 AS builder

ENV CGO_ENABLED=0 \
    GOOS=linux

WORKDIR /build

COPY go.mod go.sum ./
COPY vendor ./vendor
ENV GOFLAGS=-mod=vendor

COPY internal ./internal
COPY cmd/producer ./cmd/producer

RUN go build -o producer ./cmd/producer

FROM alpine:latest

WORKDIR /app
COPY --from=builder /build/producer .

CMD ["./producer"]
