apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          env:
            - name: APP_ENV
              value: "{{ .Values.consumer.env.appEnv }}"
            - name: RABBITMQ_QUEUE
              value: "{{ .Values.consumer.env.rabbitmqQueue }}"       
            - name: RABBITMQ_CONN_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: rabbitmq-conn-url
            - name: DB_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: postgres-conn-url
            - name: SEND_GRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: send-grid-api-key
            - name: SEND_GRID_SENDER_IDENTITY_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: send-grid-sender-identity-email
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: slack-webhook-url