apiVersion: batch/v1
kind: Job
metadata:
  name: run-db-migrations
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: migration-volume
          mountPath: /

      initContainers:
        - name: extract-migrations
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          command: [ "sh", "-c", "cp -r /app/migrations /" ]
          volumeMounts:
            - name: migration-volume
              mountPath: /migrations

      containers:
        - name: migratedb
          image: "{{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag }}"
          env:
          - name: MIGRATION_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}
                key: migrations-url
          command: ["sh", "-c", "migrate -path /migrations -database \"$MIGRATION_URL\" up"]
          volumeMounts:
            - name: migration-volume
              mountPath: /migrations
