apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  type: NodePort  
  ports:
    - port: 15672           
      targetPort: 15672     
      nodePort: 30002
      name: management
  selector:
    app: rabbitmq          
