apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - port: 80
      targetPort: {{ .Values.producer.env.apiPort | int }}
      nodePort: 30001
