// Code generated by counterfeiter. DO NOT EDIT.
package notifierfakes

import (
	"sync"

	"github.com/ggsomnoev/sumup-notification-task/internal/notification/consumer/service/notifier"
	"github.com/sendgrid/rest"
	"github.com/sendgrid/sendgrid-go/helpers/mail"
)

type FakeSendGridClient struct {
	SendStub        func(*mail.SGMailV3) (*rest.Response, error)
	sendMutex       sync.RWMutex
	sendArgsForCall []struct {
		arg1 *mail.SGMailV3
	}
	sendReturns struct {
		result1 *rest.Response
		result2 error
	}
	sendReturnsOnCall map[int]struct {
		result1 *rest.Response
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSendGridClient) Send(arg1 *mail.SGMailV3) (*rest.Response, error) {
	fake.sendMutex.Lock()
	ret, specificReturn := fake.sendReturnsOnCall[len(fake.sendArgsForCall)]
	fake.sendArgsForCall = append(fake.sendArgsForCall, struct {
		arg1 *mail.SGMailV3
	}{arg1})
	stub := fake.SendStub
	fakeReturns := fake.sendReturns
	fake.recordInvocation("Send", []interface{}{arg1})
	fake.sendMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSendGridClient) SendCallCount() int {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	return len(fake.sendArgsForCall)
}

func (fake *FakeSendGridClient) SendCalls(stub func(*mail.SGMailV3) (*rest.Response, error)) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = stub
}

func (fake *FakeSendGridClient) SendArgsForCall(i int) *mail.SGMailV3 {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	argsForCall := fake.sendArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSendGridClient) SendReturns(result1 *rest.Response, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	fake.sendReturns = struct {
		result1 *rest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeSendGridClient) SendReturnsOnCall(i int, result1 *rest.Response, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	if fake.sendReturnsOnCall == nil {
		fake.sendReturnsOnCall = make(map[int]struct {
			result1 *rest.Response
			result2 error
		})
	}
	fake.sendReturnsOnCall[i] = struct {
		result1 *rest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeSendGridClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSendGridClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ notifier.SendGridClient = new(FakeSendGridClient)
